version: '3.7'
services:
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=inventory
      - POSTGRES_PASSWORD=inventory
      - POSTGRES_DB=little-erp
    ports:
      - '5432:5432'
    volumes:
      - ./sql/setup_database.sql:/docker-entrypoint-initdb.d/setup_database.sql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
